#!/bin/bash -e

NAME=jmpapi

case "$1" in
  remove)
    # Stop the service
    systemctl stop $NAME   || true
    systemctl stop $NAME@* || true

    # Uninstall service
    rm -f /etc/systemd/system/jmpapi.service
    rm -f /etc/systemd/system/jmpapi@.service
    systemctl daemon-reload
    ;;

  purge)
    rm -rf /etc/$NAME /var/log/$NAME

    # Remove user if it exists
    if getent passwd $NAME >/dev/null; then
      echo -n "Removing system user $NAME..."
      if userdel $NAME 2>/dev/null; then
        echo "done"
      else
        echo "failed"
      fi
    fi

    # Remove group if it exists
    if getent group $NAME >/dev/null; then
      echo -n "Removing system group $NAME..."
      if groupdel $NAME 2>/dev/null; then
        echo "done"
      else
        echo "failed"
      fi
    fi
    ;;
esac
