#!/bin/bash -e

NAME=jmpapi
ETC=/etc/$NAME
RUN=/var/run/$NAME
LOG=/var/log/$NAME
CONFIG=$ETC/$NAME.yaml

case "$1" in
    reconfigure|configure)
        # Install default config if one does not exist
        if [ ! -e $CONFIG ]; then
            install /usr/share/doc/$NAME/$NAME.yaml /etc/$NAME/
        fi

        # Setup permissions
        chown -R $NAME:root $ETC $RUN $LOG
        chmod 755 $ETC $RUN $LOG

        if [ -x insserv ]; then
            # Install the init.d script
            insserv -d $NAME

            # Restart the service
            service $NAME start || true

        else
            # Install the init.d script
            update-rc.d $NAME defaults 95

            # Start the service
            invoke-rc.d $NAME start || true
        fi
        ;;
esac
