#!/bin/bash -e

NAME=jmpapi
ETC=/etc/$NAME
RUN=/var/run/$NAME
LOG=/var/log/$NAME
CONFIG=$ETC/jmpapi.yaml
DOC=/usr/share/doc/$NAME

case "$1" in
    reconfigure|configure)
        # Install default config if one does not exist
        if [ ! -f $CONFIG ]; then
            ln -s $DOC/api/jmpapi-auth.yaml $ETC/
            ln -s $DOC/api/jmpapi-docs.yaml $ETC/

            cp $DOC/api/jmpapi-example.yaml $CONFIG
            chmod a-r $CONFIG # May contain secrets
        fi

        # Setup permissions
        chown -R $NAME:root $ETC $RUN $LOG
        chmod -R u+rw,g-w,o-w $ETC $RUN $LOG

        if [ -x insserv ]; then
            # Install the init.d script
            insserv -d $NAME

            # Restart the service
            service $NAME start || true

        else
            # Install the init.d script
            update-rc.d $NAME defaults 95

            # Start the service
            invoke-rc.d $NAME start || true
        fi
        ;;
esac
