#!/bin/bash -e

NAME=jmpapi

case "$1" in
  remove)
    # Stop the service
    service $NAME stop || true

    # Uninstall service
    if [ -e /etc/systemd/system/$NAME.service ]; then
      rm -f /etc/systemd/system/$NAME.service
      systemctl daemon-reload
    fi
    ;;

  purge)
    rm -rf /etc/$NAME /etc/default/$NAME /var/lib/$NAME /var/log/$NAME

    # Remove user if it exists
    if getent passwd $NAME >/dev/null; then
      echo -n "Removing system user $NAME..."
      if userdel $NAME 2>/dev/null; then
        echo "done"
      else
        echo "failed"
      fi
    fi

    # Remove group if it exists
    if getent group $NAME >/dev/null; then
      echo -n "Removing system group $NAME..."
      if groupdel $NAME 2>/dev/null; then
        echo "done"
      else
        echo "failed"
      fi
    fi
    ;;
esac
