#!/bin/bash -e

NAME=jmpapi
ETC=/etc/$NAME
RUN=/var/run/$NAME
LOG=/var/log/$NAME

case "$1" in
  install|upgrade)
    # Create group if it does not exist
    if ! getent group $NAME >/dev/null; then
      echo -n "Adding system group $NAME..."
      if groupadd -r $NAME 2>/dev/null; then
        echo "done"
      else
        echo "failed"
      fi
    fi

    # Create user if it does not exist
    if ! getent passwd $NAME >/dev/null; then
      echo -n "Adding system user $NAME..."
      if useradd -r -g $NAME $NAME 2>/dev/null; then
        echo "done"
      else
        echo "failed"
      fi
    fi
    ;;
esac
