#!/usr/bin/bash

if [ "$1" == "" ]; then
  LOG=/var/log/jmpapi/log.txt
  HOME=/etc/jmpapi
  WD=/var/lib/jmpapi

else
  LOG=/var/log/jmpapi/$1.txt
  HOME=/etc/jmpapi/$1
  WD=/var/lib/jmpapi/$1
fi

if [ ! -e $HOME/jmpapi.yaml ]; then
  >&2 echo "File does not exist $HOME/jmpapi.yaml"
  exit 1
fi

if [ ! -d "$WD" ]; then
  mkdir -m 770 "$WD"
  if [ ! -d "$WD" ]; then
    >&2 echo "File does not exist $WD"
    exit 1
  fi
fi

cd "$WD"

ARGS=$HOME/jmpapi.yaml

if [ -e $HOME/local.yaml ]; then
  ARGS+=" $HOME/local.yaml"
fi

ARGS+=" --log $LOG --log-rotate --log-rotate-dir=/var/log/jmpapi"

export PATH=$HOME/bin:$PATH

/usr/bin/jmpapi $ARGS &
